sudo: required
dist: trusty
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check -qq
script:
- source ./env.sh
- ${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}
- ${DLR} ${GLIBC_URL} -o ${GLIBC_FN}
- ${DLR} ${FRTCP_URL} -o ${FRTCP_FN}
- ${DLR} ${LNCR_URL} -o ${LNCR_ZIP}
- 
- unzip ${LNCR_ZIP} ${LNCR_FN}
- sudo tar -zxf ${ROOTFS_FN}
- cd root.x86_64
- sudo cp -f ../profile ./etc/profile
- sudo cp -bf ../mirrorlist ./etc/pacman.d/mirrorlist
- sudo cp -bf ../pacman.conf.nosig ./etc/pacman.conf
- sudo sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" ./etc/locale.gen
- echo "LANG=en_US.UTF-8" | sudo tee ./etc/locale.conf
- sudo cp -f ../${GLIBC_FN} ../${FRTCP_FN} ./root/
- sudo cp -f /etc/resolv.conf ./etc/resolv.conf
- sudo mv -f ./etc/mtab ./etc/mtab.bak
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- 
- sudo mount -t proc proc proc/
- sudo mount --bind /sys sys
- 
- sudo chroot . /usr/sbin/pacman -Syu --noconfirm bzip2 coreutils diffutils gawk gcc-libs gettext grep gzip inetutils iproute2 iputils less man-db man-pages nano sed tar vi vim wget which
- sudo rm -rf ./etc/mtab
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- sudo chroot . /usr/sbin/locale-gen
- yes | sudo chroot . /usr/sbin/pacman -U --force  /root/${GLIBC_FN}
- yes | sudo chroot . /usr/sbin/pacman -U --force /root/${FRTCP_FN}
- yes | sudo chroot . /usr/sbin/pacman -Scc
- 
- sudo umount ./{sys,proc}
- sudo mv -f ./etc/mtab.bak ./etc/mtab 
- sudo cp -f ../pacman.conf ./etc/pacman.conf
- echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." | sudo tee ./etc/resolv.conf
- 
- sudo tar -zcf ../rootfs.tar.gz *
- sudo chown `id -un` ../rootfs.tar.gz
- cd ..
- 
- mkdir out
- mv -f ${LNCR_FN} ./out/
- mv -f rootfs.tar.gz ./out/
- cd out
- zip Arch.zip *
- ls -la
